name: Publish VSIX

on:
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        submodules: 'true'
        fetch-depth: '0'
    - name: Download artifact - win64
      id: download-win32
      uses: dsaltares/fetch-gh-release-asset@master
      with:
        repo: shader-slang/slang
        file: 'slang-.*-win64\.zip'
        target: "./"
        regex: true
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1
    - name: Copy Slang binaries and Build VSIX
      run: |
        Expand-Archive -Path slang-${{ steps.download-win32.outputs.version}}-win64.zip -DestinationPath .\SlangServer
        MSBuild.exe SlangClient.sln -v:m -m -property:Configuration=Release
    - uses: actions/upload-artifact@v3
      with:
        name: slang-vs-extension-vsix
        path: |
          bin/Release/*.vsix
